### ISSUE TITLE
Product with calculation not supported

### ISSUE THREAD

**Issue by tyxla** [tyxla/Gravity-Forms-Multiple-Form-Instances#16]
https://wordpress.org/support/topic/issue-when-using-product-calculation-field?replies=1

**Comment by tyxla** [comment]
Fixed: https://github.com/tyxla/Gravity-Forms-Multiple-Form-Instances/commit/ea5558a052bc6b27d6f159b6714d694feeeb2202

**Comment by praveenrchauhan** [comment]
Hi Marin,

Thanks for opening this issue here.

I still have a few problems dependent upon the previous one.
The product calculation fields are working now. Great !!! 
Thanks for adding this fix and updating the plugin. But the problem which still persists there is - 
The total price is not being reflected by the calculation fields. 

I also tried with adding the below code in your plugin but it did not work -
<code>
"jQuery('.ginput_total_'+". form['id'].")"     =>    "jQuery('.ginput_total_'+".$random_id.")" 
'window["gform_product_total"]('.$form['id']    =>   'window["gform_product_total"]('.$random_id,
'gformCalculateTotalPrice('.$form['id'] => 'gformCalculateTotalPrice('.$random_id,
</code>

Please Note:
The total price is being reflected by other field types such as radio field type of the product field but not by calculation field.

Can you please check for a form having following type of fields and see if all of them work (somehow, I'm not getting all of them work) ?
- Product field as radio field type and quantity field associated with it.
- Product field as calculation field.
- Total field

Thanks again for your efforts!!!

**Comment by tyxla** [comment]
Hi Praveen,

Thanks for your detailed report, I will have a detailed look later today!

**Comment by praveenrchauhan** [comment]
Sure. I'm eagerly waiting for this fix.

**Comment by tyxla** [comment]
Hi Praveen,

I've just pushed a fix: https://github.com/tyxla/Gravity-Forms-Multiple-Form-Instances/commit/cc7204713fd79c96411da9d4311a57cb58b9d67b - it appears to work fine for me now.

Can you please pull the latest version (from Git) and test with it?

If it works for you as well, I'll release a new minor version.

Looking forward to your reply.

**Comment by praveenrchauhan** [comment]
Hi Marin,

This fix worked. Awesome!!!
However there is still a disappointment for me :( Your plugin says that it works with multiple form instances and it really works what it says but my use case is bit different, however I know your plugin does not promise to work for that use case, so it's OK.

My use case:
I have a form with around 500 fields. The form was working fine earlier with less no. of fields but when I kept on adding the fields and it crossed around 400 fields, I saw lag in some fields which was very bad for the users. I analyzed and found that the conditional logic and calculation fields are affecting the form performance. I think, the conditional logic loop through all the fields of the form to show/hide a specific field and hence the conditional logic is slow with so many no. of fields and same is the case with calculation field where it searches for other fields in the form to perform the calculation with.

While doing a research, my co-developer came across your plugin and tried it. We noticed that the form became optimized. We thought to use this plugin but encountered issues with calculations part and hence requested you for the support. But ultimately what has happened is, after having the calculation and total fields working, the form's performance is being affected again. So, basically the problem remains the same.

I have an alternative approach where I can split my large form into different (smaller) forms and link there shortcodes with a navigation, so that calculation and conditional logic loop through in less no. of fields. But that is not what I was actually looking for.
Not sure if you could help me with a solution for this problem, however I know that your plugin is not intended for it. 

In all, I got prompt responses and great support from you. Not in my case but at least for the other users, these fixes addition will be helpful. Please release the new minor version as your plugin is working fine for Total and Calculation fields.

Thanks again for your support!!!

**Comment by tyxla** [comment]
Hi Praveen,

I am glad the new fix worked for you. I'll release a new version with it later today, so you will be able to update to it.

Concerning your use case: it is not possible that the lag would be caused by my plugin. What my plugin does is to essentially alter the form IDs at several necessary locations. It does nothing with altering logic or adding new stuff to it. I can suggest that you bring up your issue to the Gravity Forms core support, as this appears to be an issue on their side. 

And as a developer I can see that the way they're handling the conditional logic is, to say the least, ugly, non-effective and potentially performance-impacting. But that should be brought up with their support, as it makes sense to not have an impact on performance with more fields (as it does happen in your case).

As a current solution, I can suggest that you split your large form into either multiple forms or 1 form with multiple pages. This would reduce the impact you have on performance.

Thanks for the detailed instructions for reproducing bugs, they've been very helpful.

I wish you good luck with your project.

Regards,
Marin

**Comment by praveenrchauhan** [comment]
Yes off course, your plugin is not causing the performance issue rather it's a Gravity forms core issue.
And at least for now, I'll have to stay with the solution of splitting the form into multiple forms which I'm anyways doing.

Thanks!!!
